In [1]:
import numpy as np

In [2]:
def compute_entropy(arr):
    ratio = np.sum(arr)/len(arr)
    if ratio == 0 or ratio == 1:
        return 0
    return -np.log2(ratio) * ratio - np.log2(1-ratio) * (1-ratio)

In [3]:
num_of_q = 4
num_of_char = 10
randomTable = np.random.randint(2, size=(num_of_char,num_of_q))
appMe = np.arange(0,num_of_char,dtype='int')
randomTable = np.concatenate((appMe[:,None], randomTable),axis=1)

In [4]:
def compute_entropy_table(table):
    entropies = []
    for j in range(1, table.shape[1]):
        entropies.append(compute_entropy(table[:,j]))
    return entropies

In [5]:
'''
Helper Functions That Need Implementing:
1. get_max_index
2. subset
'''
#Helper Functions
def get_max_index(arr):
    if np.max(arr) == 0:
        return None
    return np.argmax(arr) + 1

def subset(table, col_index, value):
    #subset the table by all rows where the col given by col_index, is equal to value
    return table[table[:,col_index]==value, :]

In [6]:
'''
Given a table computes the best question to ask
'''
def give_next_question(table):
    entropies = compute_entropy_table(table)
    return get_max_index(entropies)  

In [7]:
'''
Main function manipulate table
'''
def compute_next_table(table, question_ind, answer):
    #subset the table by rows based on the question and answer
    new_table = subset(table, question_ind, answer)
    #get rid of the column where we asked the question to avoid asking it again
    new_table[:,question_ind] = 0
    return new_table

In [8]:
table = randomTable
print(table)
while give_next_question(table) != None and table.shape[0] >= 2:
    next_q = give_next_question(table)
    print("Question to Answer: ", next_q)
    ans = int(input("Answer(0/1): "))
    table = compute_next_table(table, next_q, ans)
    print(table)

[[0 1 0 1 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [3 1 1 1 1]
 [4 0 0 0 0]
 [5 1 1 1 1]
 [6 0 1 0 1]
 [7 1 0 1 1]
 [8 1 1 0 1]
 [9 1 1 0 1]]
Question to Answer:  3
Answer(0/1): 1
[[0 1 0 0 0]
 [2 1 1 0 0]
 [3 1 1 0 1]
 [5 1 1 0 1]
 [7 1 0 0 1]]
Question to Answer:  2
Answer(0/1): 1
[[2 1 0 0 0]
 [3 1 0 0 1]
 [5 1 0 0 1]]
Question to Answer:  4
Answer(0/1): 1
[[3 1 0 0 0]
 [5 1 0 0 0]]
